name: Delete Tags

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  delete_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: Authenticate with GitHub
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Fetch all tags
        run: |
          git fetch --tags

      - name: List and Delete Tags
        run: |
          echo "Fetching tags starting with ${{ github.event.inputs.tag_type }}"
          tags=$(git tag -l 'dev*' 'qa*' 'qa2*' 'tics*')
          
          if [ -z "$tags" ]; then
            echo "No tags found starting with '${{ github.event.inputs.tag_type }}'"
            exit 0
          fi

          for tag in $tags; do
            echo "Deleting tag $tag"
            #git push --delete origin "$tag" || echo "Failed to delete remote tag $tag"
            #git tag -d "$tag" || echo "Failed to delete local tag $tag"
          done
